####################################################
#                                                  #
#                   ORP Piscine                    #
#                   Metriques                      #
# ORP stands for oxidation-reduction potential, which is
# a measure, in millivolts, of the tendency of a chemical
# substance to oxidize or reduce another chemical substance.
####################################################

#input_boolean:
#  pisc_orp_metrique_yaml:
#    name: "A voir plus tard pisc_orp_metrique.yaml"

sensor:
  # - platform: history_stats
  #   name: chlore_derniere_heure
  #   entity_id: switch.ppe_chlore
  #   state: 'on'
  #   type: time
  #   end: '{{now().replace(minute=0).replace(second=0)}}'
  #   duration: 01:00:00

  # - platform: history_stats
  #   name: chlore_derniere__48h
  #   entity_id: switch.ppe_chlore
  #   state: 'on'
  #   type: time
  #   end: '{{now()}}'
  #   duration: 48:00:00

  # Statistiques orp
  - platform: statistics
    name: orp_stat_median
    # entity_id: sensor.orp_piscine_orp
    entity_id: sensor.mouillezalin_chlore
    state_characteristic: median
    sampling_size: 30
    #max_age:
      # minutes: 30

  - platform: statistics
    name: orp_stat_moyenne
    # entity_id: sensor.orp_piscine_orp
    entity_id: sensor.mouillezalin_chlore
    state_characteristic: average_step
    sampling_size: 30
    #max_age:
      # minutes: 30

  - platform: statistics
    name: orp_stat_standard_deviation
    # entity_id: sensor.orp_piscine_orp
    entity_id: sensor.mouillezalin_chlore
    state_characteristic: standard_deviation
    sampling_size: 30
    #max_age:
      # minutes: 30

